### ISSUE TITLE
seeder not recognized

### ISSUE THREAD

**Issue by ITwrx** [FbF/Laravel-Navigation#4]
php artisan db:seed --class=Fbf\LaravelNavigation\NavItemsTableSeeder

  [ReflectionException]  
  Class FbfLaravelNavigationNavItemsTableSeeder does not exist

thanks

**Comment by neilcrookes** [comment]
Hmm OK. I'll check it out at some point. In the meantime, can you try just copying the seed file in the package into your `app/database/seeds/` directory and run it again?

**Comment by ITwrx** [comment]
On 01/23/2014 04:25 AM, Neil Crookes wrote:

> Hmm OK. I'll check it out at some point. In the meantime, can you try
> just copying the seed file in the package into your
> |app/database/seeds/| directory and run it again?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FbF/Laravel-Navigation/issues/4#issuecomment-33112183.

thanks. i copied it over, but for some reason artisan seems to ignore
the seeder file and makes no mention of any error when running "php
artisan db:seed".

**Comment by neilcrookes** [comment]
Did you add it to the app/database/seeds/DatabaseSeeder.php file?

**Comment by ITwrx** [comment]
thanks for the help. did not know or see that.

**Comment by armababy** [comment]
use this instead `php artisan db:seed --class="Fbf\LaravelNavigation\NavItemsTableSeeder"` (double quotes). Worked for me.
