### ISSUE TITLE
Another error, when install

### ISSUE THREAD

**Issue by mishbah** [FbF/Laravel-Navigation#5]
Error message

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for fbf/laravel-navigation dev-master -> satisfiable by fbf/laravel-navigation[dev-master].
    - fbf/laravel-navigation dev-master requires baum/baum dev-develop -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

When I read this page https://github.com/etrepat/baum
I found that to install this package use `"baum/baum": "~1.0"` not `"baum/baum": "dev-develop"`

I don't know if it work or not

**Comment by neilcrookes** [comment]
Until recently the master branch of baum/baum was not compatible with Laravel 4.1, so I had to use the dev-develop branch instead. I think he's recently updated the master branch to us 4.1, so I've updated the dependency in the package too, as per baum's readme, as you suggested. There's also been a couple of issues raised with the dev-develop branch. Thanks for bringing it to my attention
